"""
Canonical categories and multilingual synonym dictionaries for user profile normalization.
"""

from __future__ import annotations

TRAVEL_STYLE_CATEGORIES = [
    "Business Traveler",
    "Couple Traveler",
    "Family traveler",
    "Group traveler",
    "Solo traveler",
]

TRAVEL_STYLE_SYNONYMS = {
    "Business Traveler": {
        "business traveler",
        "business travel",
        "business trip",
        "corporate traveler",
        "work trip",
        "出張",
        "ビジネス",
        "仕事の旅行",
        "ビジネストリップ",
        "商务旅行",
        "商務旅行",
        "出差",
    },
    "Couple Traveler": {
        "couple traveler",
        "couple trip",
        "romantic getaway",
        "partner trip",
        "travel with my partner",
        "カップル旅行",
        "夫婦旅行",
        "恋人と旅行",
        "デート旅行",
        "二人旅",
        "情侣旅行",
        "夫妻旅行",
        "恋人旅行",
        "二人旅行",
    },
    "Family traveler": {
        "family traveler",
        "family trip",
        "family travel",
        "family vacation",
        "travel with family",
        "kids travel",
        "家族旅行",
        "ファミリー旅行",
        "子連れ旅行",
        "親子旅行",
        "家庭旅行",
        "家庭出游",
        "亲子游",
        "親子遊",
        "帶孩子旅行",
    },
    "Group traveler": {
        "group traveler",
        "group trip",
        "group tour",
        "friends trip",
        "travel with friends",
        "team trip",
        "グループ旅行",
        "友達と旅行",
        "友人旅行",
        "団体旅行",
        "仲間と旅行",
        "团体旅行",
        "团体游",
        "团队游",
        "朋友一起旅行",
        "跟朋友旅行",
        "朋友一起",
        "同伴旅行",
    },
    "Solo traveler": {
        "solo traveler",
        "solo travel",
        "solo trip",
        "traveling alone",
        "travelling alone",
        "alone trip",
        "solo adventurer",
        "ひとり旅",
        "一人旅",
        "ソロ旅",
        "単独旅行",
        "一人で旅行",
        "独自旅行",
        "独自旅遊",
        "一个人旅行",
        "單人旅行",
        "獨自旅行",
    },
}

TRAVEL_FREQUENCY_CATEGORIES = [
    "1-2 times",
    "3-5 times",
    "6-10 times",
    "More than 10 times",
]

TRAVEL_FREQUENCY_SYNONYMS = {
    "1-2 times": {
        "1-2 times",
        "once or twice",
        "once or twice a year",
        "rarely travel",
        "yearly trip",
        "年に1-2回",
        "年1-2回",
        "年に一二回",
        "年に一度か二度",
        "たまに旅行",
        "一年一两次",
        "一年一次",
        "每年一兩次",
        "偶尔旅行",
    },
    "3-5 times": {
        "3-5 times",
        "three to five times",
        "a few times a year",
        "several trips a year",
        "年に3-5回",
        "年3-5回",
        "年に数回",
        "数回旅行",
        "年に三五回",
        "一年三到五次",
        "每年几次",
        "一年幾次",
        "一年三五次",
    },
    "6-10 times": {
        "6-10 times",
        "six to ten times",
        "almost monthly",
        "once a month",
        "monthly trip",
        "年に6-10回",
        "年6-10回",
        "月1回くらい",
        "ほぼ毎月",
        "年に十回未満",
        "一年六到十次",
        "几乎每月",
        "每月一次",
        "一年十次以内",
    },
    "More than 10 times": {
        "more than 10 times",
        "more than ten times",
        "very frequent traveler",
        "frequent traveler",
        "twice a month",
        "旅好き",
        "年に10回以上",
        "年10回以上",
        "月2回以上",
        "しょっちゅう旅行",
        "頻繁に旅行",
        "一年十次以上",
        "非常频繁",
        "每月多次",
        "常常旅行",
    },
}

PREFERRED_DESTINATION_CATEGORIES = [
    "Beaches",
    "Beaches;Cities",
    "Beaches;Cities;Historical Sites",
    "Beaches;Cities;Mountains",
    "Beaches;Cities;Nature/forests",
    "Beaches;Historical Sites",
    "Beaches;Historical Sites;Cities",
    "Beaches;Historical Sites;Mountains",
    "Beaches;Historical Sites;Nature/forests",
    "Beaches;Mountains",
    "Beaches;Mountains;Cities",
    "Beaches;Mountains;Historical Sites",
    "Beaches;Mountains;Nature/forests",
    "Beaches;Nature/forests",
    "Beaches;Nature/forests;Cities",
    "Beaches;Nature/forests;Historical Sites",
    "Beaches;Nature/forests;Mountains",
    "Cities",
    "Cities;Beaches",
    "Cities;Beaches;Historical Sites",
    "Cities;Beaches;Mountains",
    "Cities;Beaches;Nature/forests",
    "Cities;Historical Sites",
    "Cities;Historical Sites;Beaches",
    "Cities;Historical Sites;Mountains",
    "Cities;Mountains",
    "Cities;Mountains;Beaches",
    "Cities;Mountains;Historical Sites",
    "Cities;Mountains;Nature/forests",
    "Cities;Nature/forests",
    "Cities;Nature/forests;Beaches",
    "Cities;Nature/forests;Historical Sites",
    "Cities;Nature/forests;Mountains",
    "Historical Sites",
    "Historical Sites;Beaches",
    "Historical Sites;Beaches;Cities",
    "Historical Sites;Beaches;Mountains",
    "Historical Sites;Beaches;Nature/forests",
    "Historical Sites;Cities",
    "Historical Sites;Cities;Beaches",
    "Historical Sites;Cities;Mountains",
    "Historical Sites;Cities;Nature/forests",
    "Historical Sites;Mountains",
    "Historical Sites;Mountains;Beaches",
    "Historical Sites;Mountains;Cities",
    "Historical Sites;Mountains;Nature/forests",
    "Historical Sites;Nature/forests",
    "Historical Sites;Nature/forests;Beaches",
    "Historical Sites;Nature/forests;Cities",
    "Historical Sites;Nature/forests;Mountains",
    "Mountains",
    "Mountains;Beaches",
    "Mountains;Beaches;Cities",
    "Mountains;Beaches;Historical Sites",
    "Mountains;Beaches;Nature/forests",
    "Mountains;Cities",
    "Mountains;Cities;Beaches",
    "Mountains;Cities;Historical Sites",
    "Mountains;Cities;Nature/forests",
    "Mountains;Historical Sites",
    "Mountains;Historical Sites;Beaches",
    "Mountains;Historical Sites;Cities",
    "Mountains;Historical Sites;Nature/forests",
    "Mountains;Nature/forests",
    "Mountains;Nature/forests;Beaches",
    "Mountains;Nature/forests;Cities",
    "Mountains;Nature/forests;Historical Sites",
    "Nature/forests",
    "Nature/forests;Beaches",
    "Nature/forests;Beaches;Cities",
    "Nature/forests;Beaches;Historical Sites",
    "Nature/forests;Beaches;Mountains",
    "Nature/forests;Cities",
    "Nature/forests;Cities;Beaches",
    "Nature/forests;Cities;Historical Sites",
    "Nature/forests;Cities;Mountains",
    "Nature/forests;Historical Sites",
    "Nature/forests;Historical Sites;Beaches",
    "Nature/forests;Historical Sites;Cities",
    "Nature/forests;Historical Sites;Mountains",
    "Nature/forests;Mountains",
    "Nature/forests;Mountains;Beaches",
    "Nature/forests;Mountains;Cities",
    "Nature/forests;Mountains;Historical Sites",
]

PREFERRED_DESTINATION_COMPONENT_SYNONYMS = {
    "Beaches": {
        "beach",
        "beaches",
        "coast",
        "coastal",
        "seaside",
        "sea side",
        "ocean",
        "shore",
        "砂浜",
        "ビーチ",
        "海辺",
        "海岸",
        "海水浴",
        "浜辺",
        "海のそば",
        "海滩",
        "海邊",
        "沙滩",
        "沙灘",
        "海滨",
    },
    "Cities": {
        "city",
        "cities",
        "urban",
        "downtown",
        "city stroll",
        "street food",
        "都会",
        "都市",
        "街歩き",
        "市内観光",
        "街ブラ",
        "都市観光",
        "市区",
        "城市",
        "城市观光",
        "城內",
    },
    "Historical Sites": {
        "historical site",
        "historical sites",
        "heritage",
        "cultural heritage",
        "history",
        "temples",
        "shrines",
        "castle",
        "遺跡",
        "歴史",
        "史跡",
        "寺社",
        "神社仏閣",
        "文化遺産",
        "古城",
        "歴史めぐり",
        "历史遗迹",
        "古迹",
        "文化遗产",
        "寺庙",
        "古城",
    },
    "Mountains": {
        "mountain",
        "mountains",
        "alps",
        "hiking",
        "trekking",
        "climbing",
        "highlands",
        "山",
        "山登り",
        "登山",
        "ハイキング",
        "高原",
        "山歩き",
        "山岳",
        "山地",
        "山の景色",
        "山景",
        "山區",
        "爬山",
        "徒步",
        "高山",
    },
    "Nature/forests": {
        "nature",
        "forest",
        "forests",
        "outdoors",
        "greenery",
        "parks",
        "national park",
        "自然",
        "森林",
        "森",
        "アウトドア",
        "自然散策",
        "自然観賞",
        "自然豊か",
        "自然風景",
        "大自然",
        "户外",
        "森林公园",
        "自然景观",
        "自然風光",
    },
}

